const beneficiaryFieldLabels = {
  structureId: 'Structure',
  referents: 'Agent(s) référent(s)',
  aidantConnectAuthorized: 'Mandat Aidant Connect',
  status: 'Statut du dossier',
  title: 'Civilité',
  usualName: 'Nom usuel',
  birthName: 'Nom de naissance',
  firstName: 'Prénom(s)',
  birthDate: 'Date de naissance',
  birthPlace: 'Lieu de naissance',
  gender: 'Genre',
  nationality: 'Nationalité',
  accomodationMode: "Mode d'hébergement",
  accomodationName: '',
  accomodationAdditionalInformation: 'Précisions hébergement',
  city: 'Ville',
  zipcode: 'Code postal',
  region: 'Région',
  streetNumber: 'Numéro de rue',
  street: 'Nom de la rue',
  addressComplement: "Complément d'adresse",
  noPhone: "N'a pas de téléphone",
  phone1: 'Téléphone 1',
  phone2: 'Téléphone 2',
  email: 'Email',
  familySituation: 'Situation familiale',
  minorChildren: "Nombre d'enfant(s) mineur(s)",
  majorChildren: "Nombre d'enfant(s) majeur(s)",
  caregiver: 'Aidant familial',
  mobility: 'Données mobilité',
  additionalInformation: 'Informations complémentaires',
  gir: 'GIR',
  doctor: 'Médecin traitant',
  healthAdditionalInformation: 'Autres informations de santé',
  socialSecurityNumber: 'N° Sécurité Sociale',
  insurance: 'Mutuelle',
  socioProfessionalCategory: 'Catégorie socio-professionnelle',
  occupation: 'Profession(s)',
  employer: 'Employeur',
  employerSiret: "SIRET de l'employeur",
  mainIncomeSource: 'Natures des ressources',
  mainIncomeAmount: 'Montant des ressources',
  unemploymentNumber: 'N° Pôle Emploi',
  pensionOrganisations: 'Organismes de retraite',
  cafNumber: 'N° CAF',
  bank: 'Banque',
  funeralContract: 'Contrat obsèques',
  protectionMeasure: 'Mesures de protection',
  representative: 'Nom, prénom, coordonées du mandataire',
  prescribingStructure: 'Organisme prescripteur',
  orientationType: "Mode d'orientation",
  orientationStructure: "Organisme d'orientation",
  serviceProviders: 'Prestataires',
  involvedPartners: 'Partenaires intervenants',
  partnerMainIncomeSource: 'Nature des ressources du conjoint',
  partnerMainIncomeAmount: 'Montant des ressources du conjoint',
  majorChildrenMainIncomeSource: 'Nature des ressources des enfants majeurs',
  majorChildrenMainIncomeAmount: 'Montant des ressources des enfants majeurs',
  deathDate: 'Date de décès',
}

export { beneficiaryFieldLabels }
