name: Scrap preview environment
on:
  delete
jobs:
  trigger-circleci:
    if: github.event.ref_type == 'branch'
    name: Trigger CircleCI web_app_preview_deletion workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI workflow
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_CI_TOKEN }}
          project-slug: inclusion-numerique/mon-suivi-social
          # Branch from environment has been deleted, workflow will run from branch dev
          branch: dev
          payload: '{"trigger_workflow": "web_app_preview_deletion", "scrap_environment_for_branch": "${{ github.event.ref }}"}'
